#!/usr/bin/env python3
"""
Builds the game's launcher icon from a pixel-art grid.

The icon is the logo mark redrawn as pixel art: each character below is one
pixel (G = green, t = teal, Y = lime, . = empty). Edit the grid, run
`python3 tools/make_icon.py` from the project root, and the icon files in
app/src/main/res/ are rewritten:

  - drawable/ic_launcher_foreground.xml   the pixels, as a vector drawable
  - values/ic_launcher_background.xml     the black background color

Android combines them into an adaptive icon (see mipmap-anydpi-v26/ic_launcher.xml).
Each pixel is 2dp, so the 27 x 27 grid becomes a 54dp picture in the middle of
the 108dp icon canvas, which keeps it inside the safe area of every icon shape.
"""
import os

PIXEL_DP = 2
CANVAS_DP = 108

COLORS = {
    "G": "#00E676",  # green
    "t": "#00B894",  # teal
    "Y": "#C6FF3D",  # lime
}

GRID = [
    "...........................",
    "............GGG.....YY.....",
    ".........GGGG.GGGG..YY.....",
    ".......GGGG.....GGGG.......",
    ".....GGGG.........GGGG.....",
    "...GGGG.............GGGG...",
    "..GG...................GG..",
    "..GG...............YY..GG..",
    "...................YY..GG..",
    "..ttt.............YYY..GG..",
    "..ttt............YYYY..GG..",
    "..ttt..........YYYYYY..GG..",
    "............GGGGYYYY...GG..",
    "..GG.....tGGGGGGYY.....GG..",
    "..GG...tttGGGGGG...........",
    "..GG..tttttG..........YYY..",
    "..GG..tttt............YYY..",
    "..GG..ttt.............YYY..",
    "..GG..tt...................",
    "..GG..tt...............GG..",
    "..GG...................GG..",
    "...GGGG.............GGGG...",
    ".....GGGG.........GGGG.....",
    ".......GGGG.....GGGG.......",
    ".........GGGG.GGGG.........",
    "............GGG............",
    "..........................."
]

BACKGROUND = "#000000"


def path_data(rows, ch):
    """Rectangles for one color, merging neighbours in a row into a single wide rectangle."""
    offset = (CANVAS_DP - len(rows) * PIXEL_DP) // 2
    parts = []
    for y, row in enumerate(rows):
        x = 0
        while x < len(row):
            if row[x] == ch:
                start = x
                while x < len(row) and row[x] == ch:
                    x += 1
                width = (x - start) * PIXEL_DP
                parts.append(f"M{offset + start * PIXEL_DP},{offset + y * PIXEL_DP}h{width}v{PIXEL_DP}h-{width}z")
            else:
                x += 1
    return "".join(parts)


def main():
    res = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")
    assert all(len(r) == len(GRID) for r in GRID), "grid must be square"

    paths = []
    for ch, color in COLORS.items():
        data = path_data(GRID, ch)
        if data:
            paths.append(f'    <path\n        android:fillColor="{color}"\n        android:pathData="{data}" />')
    vector = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tools/make_icon.py from the pixel grid. Edit the grid, not this file. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{CANVAS_DP}dp"\n    android:height="{CANVAS_DP}dp"\n'
        f'    android:viewportWidth="{CANVAS_DP}"\n    android:viewportHeight="{CANVAS_DP}">\n'
        + "\n".join(paths) + "\n</vector>\n"
    )
    with open(os.path.join(res, "drawable", "ic_launcher_foreground.xml"), "w") as f:
        f.write(vector)

    colors = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tools/make_icon.py -->\n'
        f'<resources>\n    <color name="ic_launcher_background">{BACKGROUND}</color>\n</resources>\n'
    )
    with open(os.path.join(res, "values", "ic_launcher_background.xml"), "w") as f:
        f.write(colors)
    print("Icon files written.")


if __name__ == "__main__":
    main()
